### ISSUE TITLE
Better query logging capabilities

### ISSUE THREAD

**Issue by woodworker** [doctrine/mongodb#151]
The logging capabilities in the mongodb Odm are not as good as they could be.

I would like to have similar functionality to the doctrine orm SQLLogger Interface
see https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Logging/SQLLogger.php

i could think of some ways to do this

1. a second parameter for a after log method
 * makes getloggerCallable incompatible and looksugly
2. a new method in Doctrine\MongoDB\Configuration
 * setAfterQueryLoggerCallable
 * not a good solution to add new config parameter for every new logging case
3. make setLoggerCallable incompatible and use a similar interface like Doctrine ORM SQLLogger
 * BC break

Any other ideas or comments?

PS: i would contribute a patch for this feature request when there is consensus for a solution

**Comment by jmikola** [comment]
Closing this due to #153 also being closed. AFAIK, you were able to get by with driver's [stream context listeners](http://php.net/manual/en/mongo.context.php).
