### ISSUE TITLE
Query builder support for new sort arguments in MongoDB 2.6

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb#152]
> MongoDB 2.6 includes a $text query operator. There's a new projection syntax for including each result's relevance in the output. There's also a new syntax for sorting by relevance descending:
> 
> ```
> db.test.createIndex({s: 'text'})
> db.test.insert({s: 'spam'})
> db.test.insert({s: 'spam eggs and spam'})
> db.test.insert({s: 'sausage and eggs'})
> db.test.find(
> ...   // query
> ...   {$text: {$search: 'spam'}},
> ...   // new projection syntax
> ...   {_id: false, s: true, score: {$meta: 'textScore'}}
> ... ).sort(
> ...   // new sort syntax
> ...  {score: {$meta: 'textScore'}}
> )
> { "s" : "spam eggs and spam", "score" : 1.25 }
> { "s" : "spam", "score" : 1.1 }
> ```
> 
> Drivers probably already support the new projection syntax, since it's a similar structure to the [$elemMatch projection operator](http://docs.mongodb.org/manual/reference/operator/projection/elemMatch/).
> 
> If a driver has been validating that the _value_ portion of a sort specifier is 1, -1, or a string, it should now also allow a subdocument as the value, possibly with $-prefixed field names.

**Comment by ByScripts** [comment]
Why this merge was present in 1.1.7 but disappeared in 1.1.8 ?

**Comment by jmikola** [comment]
@ByScripts: Thanks for catching that. It looks like I screw up tagging 1.1.8 and it's missing commits from 1.1.7. Will look into this now.

**Comment by jmikola** [comment]
@ByScripts: Should be fixed now: https://github.com/doctrine/mongodb/releases/tag/1.1.7. Deleting and correcting the tag was unfortunate, but I didn't want to leave it in place, as folks might be inadvertently using code from 1.2.x that would only disappear on the next update to a 1.1.x tag (such as 1.1.8).
