### ISSUE TITLE
Expr equals() conflicts with other operators

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb#181]
Originally reported in: doctrine/mongodb-odm#917

User attempted to use `->equals('foo')` and `->notEquals('bar')` on the same field, which clashes. If `equals()` is used first, other operators will throw a PHP warning because the field cannot be access as an array (or probably worse undefined behavior if it actually is an array). Inversely, `equals()` would simply overwrite previously applied operations.

**Comment by alcaeus** [comment]
Ping @jmikola Wasn't this fixed with #201?

**Comment by jmikola** [comment]
@alcaeus: Yes, I believe so. Good catch!
