### ISSUE TITLE
MongoCollection::createIndex vs deprecated ensureIndex

### ISSUE THREAD

**Issue by senkal** [doctrine/mongodb#206]
Hi,
Since PECL mongo 1.5.0 `\MongoCollection` supports `::createIndex`(http://php.net/manual/en/mongocollection.createindex.php) and `::ensureIndex` is deprecated(http://php.net/manual/en/mongocollection.ensureindex.php). 
Couldn't find createIndex in MongoCollection wrapper class.
Are there any plans to implement this feature ?

In my project I prefer not to use deprecated methods so I go down do `\MongoCollection` and create indexes there(`createIndex`) on my dynamic time series data collections.

If this is planned or implemented then I'm sorry but I couldn't find it anywhere in code or issues.

**Comment by jmikola** [comment]
Despite the documentation, the methods are actually identical (see [here|https://github.com/mongodb/mongo-php-driver/blob/b0bd414d5c008b7914aa26b4173527e2a9e85dda/collection.c#L1924]) apart from `createIndex()` no longer allowing a scalar `$keys` argument (only an array is accepted). `ensureIndex()` will absolutely not be removed in the 1.x version of the driver, so I saw no reason to add more version detection and an extra code path in this library for `createIndex()`.

I'll close this out, as I don't believe there is anything to fix.

**Comment by senkal** [comment]
Agree.
Didn't know they are the same.

**Comment by LikeBtn** [comment]
MongoDB 3.2.9

doctrine:mongodb:schema:update command shows the following error:

`Index with name: index_name_here already exists with different options`

**Comment by malarzm** [comment]
@LikeBtn I'd suggest recreating problematic indexes.
