### ISSUE TITLE
EagerCursor does not support sorting

### ISSUE THREAD

**Issue by alcaeus** [doctrine/mongodb#208]
The ```Doctrine\MongoDB\EagerCursor``` class wraps ```Doctrine\MongoDB\Cursor```, but does not offer methods like ```sort()```. Instead, they must be called using ```$eagerCursor->getCursor()->sort()```. While this works, it also means that the two cursor classes are not interchangeable.
Note: this trickles down to the ODM as well, since the ODM\EagerCursor class also does not support sorting which in turn causes other errors. IMO, the EagerCursor class should also offer the sort methods.

**Comment by alcaeus** [comment]
Ping @jmikola Any feedback on this one?

**Comment by lavoiesl** [comment]
There should be an interface for that.

**Comment by malarzm** [comment]
For the record: ODM for now has a "quickfix" unwrapping ``EagerCusror``. I agree that common interface would be nice and should land here :)

**Comment by alcaeus** [comment]
I agree. I assume this interface should probably offer all methods that ```MongoCursor``` offers?

**Comment by alcaeus** [comment]
The PR contains a common interface - feedback is greatly appreciated!

**Comment by jmikola** [comment]
Will try to take a look in the next couple of days.

**Comment by alcaeus** [comment]
Closing this to consolidate discussion in #209.
