### ISSUE TITLE
Confused about versioning

### ISSUE THREAD

**Issue by kidbrax** [doctrine/mongodb#210]
According to http://www.doctrine-project.org/projects/mongodb-odm.html, the latest version is 1.0.0-BETA12.  But I also see tags for 1.1.x and changelog references to 1.2.  So was just wondering if you are skipping to 1.1 or has 1.0 been released.  It seems to have been in beta for quite some time.  Just trying to get an idea of what version I should be using.

**Comment by kidbrax** [comment]
I may be confused between this repo and https://github.com/doctrine/mongodb-odm?  Do they serve different purposes?

**Comment by malarzm** [comment]
Please take a look at @jwage answer here: https://github.com/doctrine/mongodb-odm/issues/1071#issuecomment-88979461

**Comment by kidbrax** [comment]
Thank you.  So does mongodb-odm use mongodb under the hood and is only meant to be used that way?  doctrine/mongodb's documentation link just points to mongodb-odm.  Does it have its own documentation anywhere?

**Comment by jwage** [comment]
@kidbrax Yes, mongodb-odm uses mongodb under the hood but the mongodb lib can be used standalone as a raw way to interact with mongodb. No standalone docs exist for https://github.com/doctrine/mongodb
