### ISSUE TITLE
Mapping types to/from mongo

### ISSUE THREAD

**Issue by jaymecd** [doctrine/mongodb#211]
Hi there,

Is there any chance that type classes from [Doctrine/ODM/MongoDB/Types](https://github.com/doctrine/mongodb-odm/tree/master/lib/Doctrine/ODM/MongoDB/Types) would become a part of this library to convert data between PHP and MongoDB instead of ODM, as well as DBAL has them w/o ORM? That would simplify a lot mongodb abstraction, where ODM is not required.

Thank you

**Comment by alcaeus** [comment]
The new MongoDB driver planned to add type conversion from BSON types to their respective PHP types, which would make this functionality obsolete. That, paired with the fact that we're retiring this (with [mongodb/mongodb](https://packagist.org/packages/mongodb/mongodb) taking its place) when releasing ODM 2.0, there's no point in adding this.

**Comment by jmikola** [comment]
The relevant JIRA ticket for `ext-mongodb` is [PHPC-640](https://jira.mongodb.org/browse/PHPC-640).
