### ISSUE TITLE
Fatal error on php: 5.3.6

### ISSUE THREAD

**Issue by stanimir-kukudov** [doctrine/mongodb#230]
Hello,

The error is: 
Fatal error: Can't inherit abstract function Countable::count() (previously declared abstract in Doctrine\MongoDB\CursorInterface) in doctrine/mongodb/lib/Doctrine/MongoDB/CursorInterface.php on line 29

This interface extends another 2 interfaces and in one of them the count method is again presented

**Comment by jmikola** [comment]
This appears to have been fixed in 5.3.9 (see: https://3v4l.org/8IhrJ).

@alcaeus: Can we slip this in to the 1.2.1 release? I'd be in favor of commenting out the declaration with a note about <=5.3.8 having a problem.

**Comment by alcaeus** [comment]
Yeah, I'll remove the count declaration entirely. There's no change to the original declaration, so I think we're safe removing it entirely, unless you want to keep the docs around?
