### ISSUE TITLE
Support for ext-mongodb

### ISSUE THREAD

**Issue by MidnightDesign** [doctrine/mongodb#239]
Are there any plans to support the new [ext-mongodb](https://pecl.php.net/package/mongodb) extension? The deprecated [ext-mongo](https://pecl.php.net/package/mongo) [doesn't support](https://docs.mongodb.org/ecosystem/drivers/php/#language-compatibility) PHP 7.

**Comment by RonXS** [comment]
I was able to work around this problem by forking the doctrine repositories and updating the requirement to mongodb 1.1 instead of mongo

My forks as an example:

https://github.com/Wizkunde/mongodb.git
https://github.com/Wizkunde/mongodb-odm.git
https://github.com/Wizkunde/DoctrineMongoDBBundle.git

**Comment by MidnightDesign** [comment]
So the API is of mongo and mongodb is exactly the same?

**Comment by RonXS** [comment]
I'm currently testing if there are any issues with it, it installs properly. My application also runs properly. Saving to mongo and querying to mongo is something that i'm going to test next.

I don't expect a lot of problems with it to be honest. But ill keep you posted.

**Comment by jmikola** [comment]
> updating the requirement to mongodb 1.1 instead of mongo

Was that a typo? Your repositories have the `ext-mongodb` dependency as ">=1.0". 1.1 has yet to be released.

The `ext-mongo` and `ext-mongodb` APIs are not at all similar. My assumption is that you've simply changed the Composer requirement, which affects platform checks, both extensions are still loaded by PHP, and Doctrine is still using the original extension.

**Comment by MidnightDesign** [comment]
So doctrine/mongodb does need to be updated in order to work with PHP 7, right?

**Comment by RonXS** [comment]
Yes, i tested it and definitely there are issues. MongoDB is installed, but the API of mongodb is actually quite different. Therefor we're stuck at php 5.* until the doctrine maintainers update the latest version to a 7.0 compatible version. (One of the issues that i immediatly run into is that it's looking for old classes like MongoId that are no longer there)

(For the record, i've verified that mongodb is installed and enabled, (output from phpinfo):

mongodb version	1.0.0alpha3

**Comment by MidnightDesign** [comment]
Oh, okay, got it: ext-mongo is being replaced by [mongodb/mongodb](https://github.com/mongodb/mongo-php-library), which is an abstraction for ext-mongodb written in PHP. So I guess this package need to be updated to depend on mongodb/mongodb, which [has an API similar to ext-mongo](https://github.com/mongodb/mongo-php-library#mongodb-library-for-php).

@jmikola, I just saw that you're actually a maintainer at [mongodb](https://github.com/mongodb). Can you give us some insight into the whole thing? This keeps me from upgrading some of my projects to PHP 7.

**Comment by alcaeus** [comment]
I'm not @jmikola, but here goes:
* ext-mongo is being replaced by [mongo-php-driver (ext-mongodb)](https://github.com/mongodb/mongo-php-driver). The new driver provides basic functionality to be extended by a userland library
* MongoDB provides such a userland library in [mongo-php-library](https://github.com/mongodb/mongo-php-library)

We haven't yet decided exactly on how we'll handle the migration to PHP 7 and ext-mongodb other than "it will happen".

**Comment by MidnightDesign** [comment]
That clears thing up. Thanks!

**Comment by luispabon** [comment]
:+1:

**Comment by ChubV** [comment]
Any news or plans on this issue?

**Comment by pilou** [comment]
+1 on ext-mongodb support

**Comment by amcsi** [comment]
+1

**Comment by alcaeus** [comment]
I'm locking this for "+1" defense. We will post an update once there is something to know.

**Comment by alcaeus** [comment]
So, after quite some time and with the upcoming release of doctrine/mongodb 1.4 I think there is some more information to be told.

First of all, this library won't be adapted to work with the new MongoDB driver. Most of the functionality is well covered by [mongodb/mongodb](https://packagist.org/packages/mongodb/mongodb). Any functionality we'll find missing while migrating ODM to the new driver might be either added to ODM itself, a new package or (most preferably) to mongodb/mongodb.

As for PHP 7 support, you can run ODM (or this library for that matter) on PHP 7 by using [alcaeus/mongo-php-adapter](https://packagist.org/packages/alcaeus/mongo-php-adapter). That library provides the legacy driver API on top of the new MongoDB driver and serves as an interims package until we have ported ODM to use the new driver natively. Once that is complete, we will release ODM 2.0 with full support for the new driver.
