### ISSUE TITLE
Aggregation: expression dateToString() return a wrong result

### ISSUE THREAD

**Issue by acrozes** [doctrine/mongodb#249]
As is tested in Doctrine\MongoDB\Tests\Aggregation\ExprTest,
```
$expr->dateToString('%Y-%m-%d', '$dateField')
```
return 
```
{ "$dateToString": [ "%Y-%m-%d", "$dateField" ] } }
```
but it should return
```
{ $dateToString: { format: "%Y-%m-%d", date: "$dateField" } }
```
see: https://docs.mongodb.org/manual/reference/operator/aggregation/dateToString/

**Comment by malarzm** [comment]
#249 has been merged :)
