### ISSUE TITLE
Latest documentation is a 404

### ISSUE THREAD

**Issue by ctrlaltdylan** [doctrine/mongodb#260]
http://docs.doctrine-project.org/projects/doctrine-mongodb/latest/en

**Comment by malarzm** [comment]
Unfortunately we don't have dedicated documentation for this project, but many things are described in [ODM's documentation](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/)

**Comment by alcaeus** [comment]
This is a problem with the doctrine website itself, so I've created doctrine/doctrine-website-sphinx#140 to track this.
