### ISSUE TITLE
Allow to pass driver options to MongoClient

### ISSUE THREAD

**Issue by tlenclos** [doctrine/mongodb#266]
Hi,
I can't find a way to pass driver options to the MongoClient class.

``` php
$this->mongoClient = $this->retry(function() use ($server, $options) {
    return new \MongoClient($server, $options);
});
```

https://github.com/doctrine/mongodb/blob/49433f0e4f9cb00f49a73e579bb36e32e348ebd6/lib/Doctrine/MongoDB/Connection.php#L281

**Comment by alcaeus** [comment]
Second constructor argument in the same class you just linked: https://github.com/doctrine/mongodb/blob/49433f0e4f9cb00f49a73e579bb36e32e348ebd6/lib/Doctrine/MongoDB/Connection.php#L79

**Comment by tlenclos** [comment]
I'm talking about the third argument of the MongoClient class which is $driver_options.

**Comment by alcaeus** [comment]
My apologies - I keep getting those two arguments confused. There is currently no way to pass in that option, unless you create the MongoClient object yourself and pass that as the first constructor argument. That way, you can set driverOptions directly.

**Comment by tonicospinelli** [comment]
@alcaeus and @tlenclos in my application I used connection options in [Connection String](https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options), take a look:
```
mongodb://username:password@db1.example.net,db2.example.net:2500/?replicaSet=test&connectTimeoutMS=300000&otherOption=value
```

**Comment by tlenclos** [comment]
@tonicospinelli Thanks but this is also not the driver options, just the connections options. I will try to create the MongoClient object manually, but I think there should be an API available via this library (and the bundle).

**Comment by alcaeus** [comment]
@tlenclos Yes, definitely. I'll tag this as feature, however, we're not sure how we're continuing with this library as this builds on the legacy driver.
