### ISSUE TITLE
How do install in php7-projects

### ISSUE THREAD

**Issue by ne0h12** [doctrine/mongodb#272]
Hi. A have a question.
I use in my project php5 with mongodb. I want upgrade php5 to php7. When I install doctrine/mongodb with alcaeus/mongo-php-adapter (like @alcaeus) then requirement ext-mongo doesn't resolved. How can I get around this limitation without fork and remove requirement "ext-mongo".

Thanks.

**Comment by malarzm** [comment]
Please refer to https://github.com/alcaeus/mongo-php-adapter#installation and if the problem persists open issue in the adapter repository.

**Comment by ne0h12** [comment]
Great thanks.
