### ISSUE TITLE
Use PSR-4

### ISSUE THREAD

**Issue by caiquecastro** [doctrine/mongodb#282]
Is there any reason to not use PSR-4 instead of PSR-0?

**Comment by alcaeus** [comment]
Not exactly, but there's also no reason to use PSR-4 over PSR-0. The only benefit I can see in PSR-4 is that we could move the contents of "lib/Doctrine/MongoDB" to the "lib" folder, but that's about it.

That being said, I'm about to wrap up 1.4.0 which will be the last minor release for this library, so I don't think it's worth making that directory change just to change the autoloading standard.

**Comment by caiquecastro** [comment]
On 2.0, it will be raised the minimum PHP version to 7?

**Comment by alcaeus** [comment]
Yes. It will be at least 7.1.
