### ISSUE TITLE
socketTimeoutMS for map/reduce

### ISSUE THREAD

**Issue by chandon** [doctrine/mongodb#284]
Is there a way do set socketTimeoutMS for a specific Map/Reduce  in doctrine ? (i mean, without setting it in the global configuration, only for the specific query)

**Comment by jmikola** [comment]
[`Doctrine\MongoDB\Collection::mapReduce()`](https://github.com/doctrine/mongodb/blob/1.4.0/lib/Doctrine/MongoDB/Collection.php#L676) does handle a "socketTimeoutMS" option (parsed [here](https://github.com/doctrine/mongodb/blob/1.4.0/lib/Doctrine/MongoDB/Collection.php#L1304)) if provided alongside the other command options. The library extracts it from the remaining mapReduce command options and uses it as an argument to [MongoDB::command()](http://php.net/manual/en/mongodb.command.php). If you grep Doctrine for "splitCommandAndClientOptions" you'll see other commands that do the same.

Note that if you're using [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter), this likely isn't supported, as `ext-mongodb` does not allow specifying a socket timeout on individual operations.

**Comment by chandon** [comment]
@jmikola thanks for this feedback
