### ISSUE TITLE
Drop support for php 5.6?

### ISSUE THREAD

**Issue by garak** [doctrine/mongodb#287]
This is a proposal: create a `2.0` branch with php7-only support.
So, you can finally remove ext-mongo and require ext-mongodb, allowing php7-only projects to use this library without any adapter.

**Comment by malarzm** [comment]
@garak thanks for the proposal although this library will not be rewritten to support new driver. Main reason is that official https://github.com/mongodb/mongo-php-library is good enough and there is no direct value for us in maintaining wrapper around it. On a side note, we were announcing this in blog post about releasing 1.4.0 - http://doctrine-project.org/2016/11/22/doctrine-mongodb-release-1.4.0.html :)

**Comment by garak** [comment]
I see. But what about doctrine/mongodb-odm? It's still requiring this library, so I can't just move to mongodb/mongo-php-library

**Comment by malarzm** [comment]
doctrine/mongodb-odm is a different story :) For 2.0 we'll be relying on mongodb/mongo-php-library directly, here's an incomplete PR: https://github.com/doctrine/mongodb-odm/pull/1553
