### ISSUE TITLE
Mongo PHP Library 

### ISSUE THREAD

**Issue by petr-buchin** [doctrine/mongodb#295]
Do you guys have plans to release a new major version of this lib, which will be based on a new [Mongo PHP Library](https://github.com/mongodb/mongo-php-library) ?

**Comment by alcaeus** [comment]
This library will not be refreshed, as the `mongodb/mongodb` takes care of most things this library did. We are planning to release a new version of Doctrine MongoDB ODM that uses `mongodb/mongodb` later this year.
