### ISSUE TITLE
link to "latest documentation" returns 404

### ISSUE THREAD

**Issue by stampycode** [doctrine/mongodb#304]
Page:
http://www.doctrine-project.org/projects/mongodb.html

Link:
http://docs.doctrine-project.org/projects/doctrine-mongodb/en/latest

**Comment by malarzm** [comment]
It's true, `doctrine/mongodb` never had its own documentation. A bits of information can be found scattered around ODM's documentation. Maybe we should remove the link or somehow add a note?

**Comment by alcaeus** [comment]
See https://github.com/doctrine/doctrine-website-sphinx/issues/140. Closing here since it's a website problem.
