### ISSUE TITLE
Time for ^7.1 support only?  Moving doctrine/mongo* forward

### ISSUE THREAD

**Issue by TomHAnderson** [doctrine/mongodb#322]
I've moved DoctrineModule and DoctrineORMModule to v2.1 with PHP ^7.1 support only.  Now I need to get DoctrineMongoODMModule to support ^2.1 so zfcampus/zf-apigility-doctrine, which supports both, can move forward.

It appears to me a large rewrite of this module is necessary to use the mongodb.so (php 7.1) driver instead of mongo.so (php 5.6).  I don't think relying on `alcaeus/mongo-php-adapter` is an option anymore now that http://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html has happened.

I think in order to fix DoctrineMongoODMModule we need to fix, in order:
- [ ] doctrine/mongodb
- [ ] doctrine/mongodb-odm
- [ ] doctrine/doctrine-mongo-odm-module

I'd like feedback that this is what needs to happen and/or correct my list.  I am between projects and can devote a good amount of time this month to making this happen.

**Comment by malarzm** [comment]
@TomHAnderson would be great if you have the throughput. So one by one:

> doctrine/mongodb

This library will see no updates, it enters bug-fix-only mode. ODM 2.0 will rely on [mongodb/mongo-php-library](https://github.com/mongodb/mongo-php-library) directly.

> doctrine/mongodb-odm

@alcaeus did hell of the job already and `dev-master` branch is already using new driver. Unfortunately there are some things on the todo list before we can tag an alpha or beta release - if you have time your help will be much appreciated (but I'd defer pointing to you right place to @alcaeus)

> doctrine/doctrine-mongo-odm-module

I myself have never used Zend thus my abilities to work on the module are quite limited. If you could, then awesome!

**Comment by alcaeus** [comment]
> Unfortunately there are some things on the todo list before we can tag an alpha or beta release

Correct - unfortunately these are very dependent on my finding some time to work on them, mainly the GridFS support that needs to be rebuilt on the new library.

Once we've got the first alpha release of ODM, we would then start working on the Framework integrations, (Symfony bundle and Zend Framework module) and adapt them to the new version.

I'm closing this issue since there's nothing to do for this library.
