### ISSUE TITLE
Deprecation on next major version

### ISSUE THREAD

**Issue by xNarkon** [doctrine/mongodb#332]
`The "Doctrine\MongoDB\LoggableCollection::aggregate()" method will require a new "array $op" argument in the next major version of its parent class "Doctrine\MongoDB\Collection", not defining it is deprecated.`

**Comment by alcaeus** [comment]
This library will not be developed any further, and there will not be a new major release. With the release of Doctrine MongoDB ODM 2.0, this library will receive bug fixes for another 6 months before being marked abandoned. Please use `mongodb/mongodb` instead.
