### ISSUE TITLE
wrong required php extention

### ISSUE THREAD

**Issue by dvdknaap** [doctrine/mongodb#336]
Hi,

I want to use the bundle doctrine/mongodb-odm-bundle but composer is failing on installing because it requires ext-mongo but it's ext-mongodb.

Other doctrine repo's that is using this repo are already using ext-mongodb.
https://github.com/doctrine/mongodb-odm/blob/master/composer.json

Could you update this repo so i can use the extension ?

Thanks,

**Comment by malarzm** [comment]
ODM's master branch is not requiring this library, versions 1.x do. Closing as per https://github.com/doctrine/mongodb/pull/337#issuecomment-526510076
