### ISSUE TITLE
Cannot create collection using Database::createCollection() with MongoDB >=4.1.10

### ISSUE THREAD

**Issue by xodmqjw** [doctrine/mongodb#339]
Cannot create a collection via[ Doctrine\MongoDB\Database::createCollection()](https://github.com/doctrine/mongodb/blob/ecf566b1f753f113ed60c8db53a1134b1de59309/lib/Doctrine/MongoDB/Database.php#L115) because in this method 'max' and 'size' fields are explicitly set to 0.

```php
$options = is_array($cappedOrOptions)
            ? array_merge(['capped' => false, 'size' => 0, 'max' => 0], $cappedOrOptions)
            : ['capped' => $cappedOrOptions, 'size' => $size, 'max' => $max];

$options['capped'] = (boolean) $options['capped'];
$options['size'] = (integer) $options['size'];
$options['max'] = (integer) $options['max'];
```

Starting with 4.1.10 MongoDB does not allow to use createCollection() with set fields for 'max',  'size' and **false** value for the field 'capped':

MongoDB v.4.1.9:

```
> db.createCollection("test", {capped: false, max: 0, size: 0})
{ "ok" : 1 }
```

MongoDB v.4.1.10
```
> db.createCollection("test", {capped: false, max: 0, size: 0})
{
	"ok" : 0,
	"errmsg" : "the 'capped' field needs to be true when either the 'size' or 'max' fields are present",
	"code" : 72,
	"codeName" : "InvalidOptions"
}
```

**Comment by alcaeus** [comment]
This library is no longer maintained and will not receive bug fixes except for critical security issues. The library is built on the legacy driver, which does not support newer MongoDB releases.

If you are using this library standalone, please switch to the `mongodb/mongodb` package, which is part of the supported MongoDB driver for PHP, along with the `ext-mongodb` extension.
If you are using this library as part of MongoDB ODM, please upgrade to ODM 2.0, which is no longer built on this library. If you cannot upgrade to 2.0 yet, I would suggest running it with MongoDB 4.0 or lower until you can upgrade.
