### ISSUE TITLE
Drop doctrine/common dependency

### ISSUE THREAD

**Issue by netiul** [doctrine/mongodb#341]
This library relies on doctrine/common repository.

Even tough this library is deprecated, would it still be possible to drop the doctrine/common dependency in favor of the replacement repositories like doctrine/collections and doctrine/persistence?

It would enable one to upgrade other dependencies relying on doctrine/common >= 3.0.

**Comment by alcaeus** [comment]
If you can create a pull request, I'm willing to consider it for a final patch release.

**Comment by alcaeus** [comment]
I'm closing this library: the PR didn't go anywhere, and we're now archiving this library. If you are still using it (either as an explicit dependency or through MongoDB ODM), it's time to move upgrade and move on.
