### ISSUE TITLE
Mongo driver shouldn't be dependency

### ISSUE THREAD

**Issue by colinmeinke** [doctrine/mongodb#88]
I use vagrant for development so don't want to be forced to install the mongo driver on my local machine.

```
Problem 1
    - Installation request for doctrine/mongodb dev-master -> satisfiable by doctrine/mongodb dev-    master.
    - doctrine/mongodb dev-master requires ext-mongo * -> the requested PHP extension mongo is missing from your system.
  Problem 2
    - Installation request for doctrine/mongodb 1.0.x-dev -> satisfiable by doctrine/mongodb 1.0.x-dev.
    - doctrine/mongodb 1.0.x-dev requires ext-mongo * -> the requested PHP extension mongo is missing from your system.
  Problem 3
    - doctrine/mongodb 1.0.x-dev requires ext-mongo * -> the requested PHP extension mongo is missing from your system.
    - iampersistent/mongodb-acl-bundle dev-master requires doctrine/mongodb 1.0.x-dev -> satisfiable by doctrine/mongodb 1.0.x-dev.
    - Installation request for iampersistent/mongodb-acl-bundle dev-master -> satisfiable by iampersistent/mongodb-acl-bundle dev-master
```

**Comment by stanlemon** [comment]
@jmikola Wondering if any consideration has been given to this in light of hhvm, which includes the classes that doctrine/mongodb uses but does not seem to pass the extension requisite in composer.

**Comment by jwage** [comment]
@stanlemon We would consider it. What is your suggestion? Make the dependency require-dev? It sounds like this should be something that composer solves.

**Comment by alcaeus** [comment]
Personally, I'd rather see this solved in composer. If any other library (and be it hhvm itself) provides the same functionality as ext-mongo, the composer requirement for it should pass, period. As it is now, doctrine/mongodb requires ext-mongo to run, so it should still fail if ext-mongo (or an equivalent) is not present.

**Comment by jmikola** [comment]
For context, Composer can ignore platform requirements as of October 2014 ([this comment]( https://github.com/composer/composer/issues/1426#issuecomment-59521713)):

> Latest composer now has `--ignore-platform-reqs` in update and install to ignore `php`, `hhvm` and `ext-*` requirements.

@stanlemon: Regarding "in light of hhvm, which includes the classes that doctrine/mongodb uses", are you referring to: https://github.com/facebook/hhvm/tree/master/hphp/runtime/ext_zend_compat/mongo. I wasn't aware that any code from the extension was imported into HHVM, but that source appears to be about 2 years old.

I initially thought you were referring to [mongofill](https://github.com/mongofill/mongofill), which I assume most HHVM users may be using at present. That library, which is implemented completely in PHP, happens to provide `ext-mongo` and satisfy Doctrine MongoDB's Composer dependency.

**Comment by stanlemon** [comment]
@jmikola Yes, that's what I had in mind. It's possible it's not usable - I confess that Travis was sort of my avenue to explore it as I have a project that uses ODM. This makes me wonder if there would be an easy enough way to add mongofill for hhvm runs in travis just to see how ODM holds up.

**Comment by jmikola** [comment]
> This makes me wonder if there would be an easy enough way to add mongofill for hhvm runs in travis just to see how ODM holds up.

I did just that in https://github.com/bernardphp/bernard/pull/133. The mongofill installation is now handled by [tests/travis.sh](https://github.com/bernardphp/bernard/blob/de099e1b4af99b57459084f3d8a41c7b9e54e7da/tests/travis.sh).
